import banner from '@/assets/100.jpg';

export const exeChampionships = [
  {
    banner: banner,
    name: 'Team nadai games 2022',
    startDate: '2022-10-10',
    endDate: '2022-10-12',
    accessCode: 'NADAI23',
    resultType: 'SCORE',
    address: 'Rua Romário Vidal n 3, Vila Yolanda',
  },
  {
    banner: banner,
    name: 'Team nadai games 2022',
    startDate: '2022-10-10',
    endDate: '2022-10-12',
    accessCode: 'NADAI23',
    resultType: 'SCORE',
    address: 'Rua Romário Vidal n 3, Vila Yolanda',
  },
  {
    banner: banner,
    name: 'Team nadai games 2022',
    startDate: '2022-10-10',
    endDate: '2022-10-12',
    accessCode: 'NADAI23',
    resultType: 'SCORE',
    address: 'Rua Romário Vidal n 3, Vila Yolanda',
  },
  {
    banner: banner,
    name: 'Team nadai games 2022',
    startDate: '2022-10-10',
    endDate: '2022-10-12',
    accessCode: 'NADAI23',
    resultType: 'SCORE',
    address: 'Rua Romário Vidal n 3, Vila Yolanda',
  },
  {
    banner: banner,
    name: 'Team nadai games 2022',
    startDate: '2022-10-10',
    endDate: '2022-10-12',
    accessCode: 'NADAI23',
    resultType: 'SCORE',
    address: 'Rua Romário Vidal n 3, Vila Yolanda',
  },
  {
    banner: banner,
    name: 'Team nadai games 2022',
    startDate: '2022-10-10',
    endDate: '2022-10-12',
    accessCode: 'NADAI23',
    resultType: 'SCORE',
    address: 'Rua Romário Vidal n 3, Vila Yolanda',
  },
];
